apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-prueba
  title: Backstage Prueba - Brayan
  description: >
    Componente de prueba para aprender a registrar servicios 
    en Backstage. Creado por Brayan Zamora en Lyncorp.
  annotations:
    github.com/project-slug: zamoraB/backstage-prueba
  tags:
    - prueba
    - backstage
    - lyncorp
    - dotnet
  links:
    - url: https://github.com/zamoraB/backstage-prueba
      title: Repositorio GitHub
      icon: github

spec:
  type: service
  lifecycle: experimental
  owner: user:default/zamoraB
